#!/bin/sh
#

export SYNCTHING_APP_HOME="{{pkg.path}}"
export SYNCTHING_APP_DATA="{{pkg.svc_data_path}}"
export SYNCTHING_APP_VAR="{{pkg.svc_var_path}}"

echo "Copying config files"
pushd {{pkg.svc_config_path}}
{{#if cfg.migrate.overwrite_config}}
echo "Overwriting config"
cp -v config.xml ${SYNCTHING_APP_DATA}
{{else}}
echo "Not overwriting config if it already exists"
cp -v -n config.xml ${SYNCTHING_APP_DATA}
{{/if}}

echo "Config Status:"
cat ${SYNCTHING_APP_DATA}/config.xml
echo ""

pushd ${SYNCTHING_APP_DATA}
{{#if cfg.migrate.overwrite_keys}}
{{#if cfg.pems.key}}
echo "Writing key.pem"
echo "{{cfg.pems.key}}" > key.pem
cat key.epm
echo ""
{{/if}}

{{#if cfg.pems.cert}}
echo "Writing cert.pem"
echo "{{cfg.pems.cert}}" > cert.pem
cat cert.pem
echo ""
{{/if}}

{{#if cfg.pems.https_key}}
echo "Writing https-key.pem"
echo "{{cfg.pems.https_key}}" > https-key.pem
cat https-key.pem
echo ""
{{/if}}

{{#if cfg.pems.https_cert}}
echo "Writing https-cert.pem"
echo "{{cfg.pems.https_cert}}" > https-cert.pem
cat https-cert.pem
echo ""
{{/if}}
{{/if}}
popd

popd

echo "Linking executables from ${SYNCTHING_APP_HOME} to ${SYNCTHING_APP_VAR}"
ln -sf ${SYNCTHING_APP_HOME}/syncthing ${SYNCTHING_APP_VAR}

chown -R hab:hab ${SYNCTHING_APP_DATA}