# see here https://docs.syncthing.net/users/config.html for explanation of values
[migrate]
# whether or not to overwrite the application config upon startup
overwrite_config = false
oberwrite_keys = false

[pems]
key = ""
cert = ""
https_key = ""
https_cert = ""

[[folders]]
id = "somefolderid"
path = "test"
label = "Default Folder"
type = "readwrite"
rescan_intervals = 60
ignore_perms = false
auto_normalize = true


# [[devices]]
# id = "AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA-AAAAAAA"
# name = "test-machine"
# address = "dynamic"
# introducer = false
# compression = "metadata"

[gui]
enabled = true
tls = false
address = "127.0.0.1:8384"
apikey = ""
listen_address = "default"
theme = "default"


[options]
listen_address = "default"
start_browser = false